spring:
  datasource:
    username: root
    password: Aptx4869.
    url: jdbc:mysql://47.99.65.156:13306/mymall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 18081